### ISSUE TITLE
show how to use Dojo modules that aren't included in the ArcGIS API for JavaScript

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-webpack-babel#4]
I think it would be good if the map in this example used https://github.com/Esri/cluster-layer-js like @jwasilgeo's [plnkr](http://plnkr.co/edit/bZNzdI?p=preview) in order to demonstrate how to load Dojo modules that aren't included in the ArcGIS API for JavaScript, b/c [it can be a bit confusing](
https://github.com/Esri/angular-esri-map/issues/311).

**Comment by jwasilgeo** [comment]
I'm down to try it out.

**Comment by jwasilgeo** [comment]
I'm down to try it out. Want to assign it to me?

**Comment by tomwayson** [comment]
Thanks @jwasilgeo! Can't actually assign until you accept collaborator invite, but this one's all you.
